# Generated by Django 4.0.4 on 2022-05-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('ptype', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('pdiscount', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=5)),
                ('pdetails', models.TextField()),
            ],
        ),
    ]
