# Generated by Django 4.0.3 on 2022-05-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0002_alter_product_options_product_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdiscount',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
