# Generated by Django 4.0.3 on 2022-05-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0003_remove_product_pdiscount_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
