# Generated by Django 4.0.3 on 2022-05-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
